name : main
on: [workflow_dispatch]
jobs:
 build-msys-cross-in-ubuntu:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4.2.0
      with:
       # Repository name with owner. For example, actions/checkout
       repository: msys2/msys2-runtime
       # optional, default is ${{ github.repository }}
       # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
       fetch-depth: 1
       # optional, default is 1
    - run: sudo apt -qy install software-properties-common dnf autoconf automake libtool cpio gcc make flex yacc gcc-multilib pkg-config zstd
    #- run: sudo dnf -qy install https://github.com/rpmsphere/noarch/raw/refs/heads/master/r/rpmsphere-release-38-1.noarch.rpm
    #- run: m=$(uname -m);sudo dnf -qy install --releasever 40 https://github.com/rpmsphere/$m/raw/refs/heads/master/c/cocom-0.996-10.1.$m.rpm
    - run: m=$(uname -m);echo https://github.com/rpmsphere/$m/raw/refs/heads/master/c/cocom-0.996-10.1.$m.rpm;
           curl --compressed "https://github.com/rpmsphere/$m/raw/refs/heads/master/c/cocom-0.996-10.1.$m.rpm" -o $GITHUB_WORKSPACE/cocom-0.996-10.1.$m.rpm;
           stat $GITHUB_WORKSPACE/cocom-0.996-10.1.$m.rpm;
           rpm2cpio $GITHUB_WORKSPACE/cocom-0.996-10.1.$m.rpm|cpio -idm $GITHUB_WORKSPACE/cocom-0.996-10.1.$m;
           export PATH=$PATH:$GITHUB_WORKSPACE/cocom-0.996-10.1.$m/usr/bin;
           dino -v;
