name : main
on: [workflow_dispatch]
jobs:
 build-msys-cross-in-ubuntu:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4.2.0
      with:
       # Repository name with owner. For example, actions/checkout
       repository: msys2/msys2-runtime
       # optional, default is ${{ github.repository }}
       # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
       fetch-depth: 1
       # optional, default is 1
       path: msys2-runtime
    - run: sudo apt -qy install software-properties-common dnf autoconf automake libtool cpio gcc make flex yacc gcc-multilib pkg-config zstd g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix
    #- run: sudo dnf -qy install https://github.com/rpmsphere/noarch/raw/refs/heads/master/r/rpmsphere-release-38-1.noarch.rpm
    #- run: m=$(uname -m);sudo dnf -qy install --releasever 40 https://github.com/rpmsphere/$m/raw/refs/heads/master/c/cocom-0.996-10.1.$m.rpm
    - run: m=$(uname -m);echo https://github.com/rpmsphere/$m/raw/refs/heads/master/c/cocom-0.996-10.1.$m.rpm;
           curl -L --compressed "https://github.com/rpmsphere/$m/raw/refs/heads/master/c/cocom-0.996-10.1.$m.rpm" -o $GITHUB_WORKSPACE/cocom-0.996-10.1.$m.rpm;
           mkdir -p $GITHUB_WORKSPACE/cocom-0.996-10.1.$m;rpm2cpio $GITHUB_WORKSPACE/cocom-0.996-10.1.$m.rpm|cpio -imdD $GITHUB_WORKSPACE/cocom-0.996-10.1.$m;
           export PATH=$PATH:$GITHUB_WORKSPACE/cocom-0.996-10.1.$m/usr/bin;
           OPT="-g -O2";
           export PATH=$PATH:/usr/x86_64-w64-mingw32/bin;
           CFLAGS="-DWINVER=0x0A00 -DNTDDI_VERSION=0x0A000008 -D_WIN32_WINNT=0x0A00 ${OPT} -march=bdver4 -mtune=bdver4 -mthreads -fwrapv -fno-strict-aliasing -fvisibility=default -mstackrealign";
           p=x86_64-w64-mingw32;
           cd msys2-runtime;
           (cd winsup; ./autogen.sh);
           mkdir -p build install;
           cd build;
           guess=$(../config.guess);
           ../configure --prefix=$(realpath $(pwd)/../install) --disable-doc CC=${p}-gcc CXX=${p}-g++ --host=$guess --target=${p} CFLAGS="${CFLAGS}" CXXFLAGS="${CFLAGS}" PKG_CONFIG_PATH=/usr/${p}/lib/pkgconfig PKG_CONFIG_LIBDIR=/usr/${p}/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR= --enable-shared "$@" LTLDFLAGS='-no-undefined' lt_allow_undefined_flag=yes lt_cv_deplibs_check_method=pass_all;
           make -j4;
    #       find $GITHUB_WORKSPACE/cocom-0.996-10.1.$m -type d;
